language: node_js
node_js:
- 4.2.4
env:
  secure: E5zZ+e1h1IyWFalmzwhis+ktuRgGajeqhs5zGuTnJhHN0GNaHgvRZrDOtLhzLLy7cGBrGzP9lyouUjmtXlAMEYoIWMEN8Jys72lxZCC/f+kKtCE9RGI6kLr3Tk9h9MyoT3lG/t1cmOwgnTBio6EM72njl4x9DSvGl/hfE84mu4MSMM8DXdYG/cPNpaZAHfLnWU7wDSbjJ2da1BfHYp3z7OxSS+Lex7asu4ICk9p8oozTY4UgptETAc1kYHalF45aZ+9Z3C/JtkrllJlRKAVpnf007hztJEUCmOtmcZZAMoptOszzYuqQrFLvZKjAL30qg7exwu7RdqcvjUvkpRVb5GYSsfh8pXAZUWBQkxyWWaQedUMqTS6LSafLKChHdiS9/nMhETVdYRYmcZjCFn0qBApEzKEVgYmbUW56XN+adGKg/3I2C+n/XKAt8xOcR5uzaiPae0yg/MlsGqdPlg+l1q6pQoreRB8tkYNNlXI+NZLIJBBoW5CSPgHVQecsQNy3ICaA0oDCTncAtIVQ+eYG5nfsxR9ayvguUt4LJRVNiMHIOBxOU6CAw0UJiV5x2kTndhyMpZXXK3y5iWVkoWJHESvw9KWFi+EPgyjBk4ITfadyvxivwPY6X1sr2bxOMHf1lZ2A1dLCIEHQT84BOsuNPnK2fWG4ODD7YSOnMGLWG+A=
script:
  - npm run test
  - npm run jshint
before_deploy: npm run infra
deploy:
  provider: heroku
  app: hero-dash
  api_key:
    secure: foJ3JybzLgup71LCRFXWVG/a+XBQgJFGBcDHxOXZ98Wj6OAITaXBRnzYMBUL/mKmgWR1WxcLAjtwxMoM2dC6tNNjHsy73yrBjzaXWAQirxotuJ8xzUcy2Qs5VYcEEQKCouRDVJnjWMoD8NnukoReXGi9orIP8gYadVcJJWacqgaTMDMAP00QeVNstzC8OU9BiO5Hq9yrAqSUw0/fQXG2DbETsN8bFYaaDYUyFIclxmGmCWVGrjLkGxaCgWUHeF5ZGl7OHDLZHfi/n0WINC3T0SpidPT0RTgaU+yQ0e9hQavD4LWKVH3tFr4Ggxab0SOz49xccQjKL53pYZPHuyF+jzglZgYOe5hZBBYEsaoAWzCVevS78dyxNKAlYl1xMucNbWeiKm84ELSIvtaK4dxa9HPoPEca7mn9WCfFwpSHNPf/kJk8/kL3xa2d9Y/1H21OTZ1RbeZZyi0LzvNsm5gvrcB6v5M2yIQbIoGYiSRBBROxKE2No3rskcrny5J/jGQi0RCbWDSD4w2+t212uriIiP9gRJhvuhOxOddbwQDC0CREBjX7KNLpzONmkjQHUAJA3SJnfNdnRa1N9ad0npQiaUKv02ZzsET/EUcswFJvZ3yT0YeyWhSULc6W6C0N72DgKiQykUACSm5VoZ526s7LXT+MTjrIHEa5LIKOn2dBJ+o=
